### ISSUE TITLE
Reverse order of `dop` and `do` snippets in tab-completion pop-up

### ISSUE THREAD

**Issue by partydrone** [atom/language-ruby#139]
When I type the keyword `do` in a Ruby file, the tab completion pop-up used to show `do` first (for a block without arguments), and `dop` second (for a block with arguments).

I'm not sure which update changed that, but now they show up in reverse order: `dop`, then `do`.

![screen shot 2016-02-27 at 3 26 12 pm](https://cloud.githubusercontent.com/assets/57892/13375797/c836937e-dd66-11e5-8e61-902efca7fd98.png)

This is undesirable because when I don't need to include arguments, it introduces an additional keystroke (e.g., <tt>DOWN ARROW</tt>)—which is awkward—and breaks my rhythm when typing.

By reversing the order, I can type <tt>D</tt>+<tt>O</tt>+<tt>TAB</tt> to get

``` ruby
object.each do

end
```

And I can still type <tt>D</tt>+<tt>O</tt>+<tt>P</tt>+<tt>TAB</tt> to get

```ruby
object.each do |variable|

end
```

It flows much better that way.

**Comment by 50Wliu** [comment]
Hi @partydrone, the reason this is happening is because autocomplete-snippets had a bug where it would always return `NaN` when trying to compare strings, and so the new autocompletion logic would favor `dop` despite `do` being first alphabetically (see #130 for more details).

This *should* be fixed in the Atom 1.6.0 betas - if not, please comment over at #130 and I'll reopen the issue.
