### ISSUE TITLE
Can't set Tab Length to 2

### ISSUE THREAD

**Issue by ninoM** [atom/language-ruby#174]
So I have my editor default to a Tab Length of 4 but I want ruby to have a setting of tab length set to 2. Can't seem to do that since when I set ruby to a tab length of 2, it seems to overwrite 2 and puts in 4 instead. It doesn't do this with any number, I've tried setting it to 1, 3 and other numbers and it only does this when I set it to 2.

[This is what happens when I set it to 2.](http://i.imgur.com/F3bPEMv.gifv)

**Comment by 50Wliu** [comment]
I suspect you are on an outdated Atom version as this has already been fixed.  The latest Atom version is currently 1.11.2.

**Comment by ninoM** [comment]
[I'm using the latest Atom version](http://i.imgur.com/JzqWlyd.png)

**Comment by 50Wliu** [comment]
Please include the Atom version (and OS) in your future bug reports, since then misunderstandings like these won't occur.  I'm actually going to keep this closed as after I closed this issue I went hunting for the commit that fixed it.  Turns out that Atom 1.12 (currently in beta) [fixes](https://github.com/atom/settings-view/issues/774#issuecomment-246526499) the issue.

**Comment by ninoM** [comment]
@50Wliu Thanks so much! I will remember that next time. First time Atom user here 👍

**Comment by 50Wliu** [comment]
No problem!  Glad we were able to resolve the issue.
