### ISSUE TITLE
`group` now breaks highlighting for all characters that come after it in both .erb and .rb

### ISSUE THREAD

**Issue by Rockster160** [atom/language-ruby#195]
Since commit found [here](https://github.com/atom/language-ruby/commit/54db19f1c9a09264e61f3fddec0b09e768f5c8e0), "group" is added as a tokenized keyword. This was intended to apply to Gemfiles, but has the (assuming) unintended side effect of breaking syntax highlight in other Ruby files as well.

Examples of bad highlighting:
![screen shot 2017-03-15 at 12 09 58 pm](https://cloud.githubusercontent.com/assets/8505362/23963916/687b4148-0978-11e7-9b82-eb75e5313833.png)
![screen shot 2017-03-15 at 12 09 45 pm](https://cloud.githubusercontent.com/assets/8505362/23963917/6884338e-0978-11e7-821c-855b7dead0bc.png)
![screen shot 2017-03-15 at 12 08 29 pm](https://cloud.githubusercontent.com/assets/8505362/23963918/68855f5c-0978-11e7-97b3-9c00ae16ee4b.png)

I would definitely consider this a bug, seeing as a group can be an extremely common variable name, and not considered a reserved word in any case.

**Comment by 50Wliu** [comment]
@caleb531

**Comment by caleb531** [comment]
Well, this is embarrassing. As I see it, there are several possible solutions to this issue:

1. Revert https://github.com/atom/language-ruby/commit/54db19f1c9a09264e61f3fddec0b09e768f5c8e0 and remove syntax highlighting for `group` completely. Ironically, the `group`, `gem`, `source`, and `ruby` keywords [aren't highlighted in the Bundler docs](http://bundler.io/groups.html) (and Bundler is the project that standardized the Gemfile format). Since these are technically non-reserved keywords that aren't going to be highlighted by most Ruby syntax highlighters anyway, perhaps then it is worth removing the highlighting from Atom entirely for the sake of bugs like this.
2. Write a separate grammar rule exclusively for `group` that matches the exact syntax of a `group` declaration in Gemfiles (e.g. `group :my_group_name do`)
3. Create a separate grammar file for Gemfile-specific syntax. To avoid duplicating grammar rules (for strings and such), I'd be curious know if this Gemfile grammar can inherit the grammar rules from the existing `ruby.cson` grammar. However, I'm not familiar enough with the Atom API to know if this is possible.

Thoughts, @Rockster160 and @50Wliu?

**Comment by Rockster160** [comment]
I think 3 is the best approach. Crossed fingers that there is some way to inherit the standard Ruby syntax and simply extend it.
I'm not against 1 or 2 either. I never noticed a highlight issue in the Gemfile previously (I expected `group` not to have special highlighting), and honestly don't spend enough time in it to really mind if the highlighting is a little off- I would think others would have a similar experience, but can only speak for myself there.

**Comment by caleb531** [comment]
@Rockster160 After some digging, I found that Atom's grammar format is based on TextMate's [grammar format](https://manual.macromates.com/en/language_grammars) (and AFAIK, they are actually equivalent). Looking through the aforementioned grammar spec for TextMate, there doesn't appear to be any means of extending a grammar via an existing grammar.

[The grammar for Gemfiles](http://bundler.io/v1.5/gemfile.html) actually looks pretty simple—there are only a few formats to tokenize (`do|end|gem|group|ruby|source`, `"strings"` or `'strings'`, and `:group_names`). So even if we were to duplicate some grammar rules in a new `gemfile.cson` grammar to maximize syntax highlighting, the cost wouldn't be *that* bad.

**Comment by 50Wliu** [comment]
Yes, you can, using (for example) `'include': 'source.ruby#string'` to bring in the string pattern, or `'include': 'source.ruby'` for the whole grammar.

**Comment by caleb531** [comment]
Wow, how did I miss that? Anyway, that's fantastic! I'll begin writing a Gemfile grammar later today, and I hope to submit a PR soon. :)

**Comment by caleb531** [comment]
@50Wliu @Rockster160 Alright, I've submitted #196 which should fix this issue and even improve syntax highlighting for Gemfiles.

**Comment by 50Wliu** [comment]
Fixed by #196.
