### ISSUE TITLE
Inconsistency on symbo syntax using TreeSitter

### ISSUE THREAD

**Issue by foreverqihe** [atom/language-ruby#254]
When not using TreeSitter:
![image](https://user-images.githubusercontent.com/2378002/48940459-c1659800-ef6b-11e8-82ec-aee44cae6e3a.png)
When using TreeSitter:
![image](https://user-images.githubusercontent.com/2378002/48940471-d510fe80-ef6b-11e8-9924-ec963eb1480c.png)

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
