### ISSUE TITLE
Treating Heredocs as a code line rather than a String line

### ISSUE THREAD

**Issue by Souravgoswami** [atom/language-ruby#264]
In Atom, while writing a Ruby program, the delimiting identifier of heredocs is treated as a string, rather than a code. As a result the limit string is highlighted in green! This could be quite confusing 😕

## So for example 📸
This is how it looks in Atom ⚛️

![image](https://user-images.githubusercontent.com/37468605/58750149-3c27e680-84ac-11e9-8bc7-8bf74644c57a.png)

This is how it should look (ignore the black / dark look) ✨

![image](https://user-images.githubusercontent.com/37468605/58750507-16511080-84b1-11e9-8ed9-6d24cb2ea4a0.png)

(http://graysoftinc.com/ruby-voodoo/working-with-multiline-strings)

---

So, the EOF shouldn't be highlighted in green, how about treating it like a code rather than a String?

**Comment by calebmeyer** [comment]
Thanks for reaching out!

We require [the template](https://github.com/atom/language-ruby/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
