### ISSUE TITLE
where is the path language-ruby get installed to on Windows

### ISSUE THREAD

**Issue by vnluc** [atom/language-ruby#277]
I am trying to open language-ruby. I found it get installed but not find where this get install on Windows. I am looking at ".atom\packages" but I dont find this package.

**Comment by rsese** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

---

The `packages` directory in your Atom home directory contains your community packages - if you want to work on a core package, we have more information on how to do that in the [Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/).  And I believe the core packages are part of the `app.asar` file so you can't access the files directly.

But in any case, the best places to ask questions are mentioned above, in particular the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638).
